admin_web_mail:
    resource: "@AdminWebMailBundle/Resources/config/routing.yml"
    prefix:   /

admin_web_mail_users:
    resource: "@AdminWebMailBundle/Resources/config/routing_users.yml"
    prefix:   /users/

admin_web_mail_domains:
    resource: "@AdminWebMailBundle/Resources/config/routing_domains.yml"
    prefix:   /domains/

admin_web_mail_aliases:
    resource: "@AdminWebMailBundle/Resources/config/routing_aliases.yml"
    prefix:   /aliases/