homepage_domains:
    path:     /
    defaults: { _controller: AdminWebMailBundle:Domain:index }

get_domains:
    path:     /get
    defaults: { _controller: AdminWebMailBundle:Domain:getDomainsJSON }

get_domains_test:
    path:     /users
    defaults: { _controller: AdminWebMailBundle:Domain:getUsers }
