homepage_domains:
    path:     /
    defaults: { _controller: AdminWebMailBundle:Domain:index }

get_domains:
    path:     /get
    defaults: { _controller: AdminWebMailBundle:Domain:getDomainsJSON }

add_domains:
    path:     /add
    methods:  [POST]
    defaults: { _controller: AdminWebMailBundle:Domain:addDomain }


delete_domains:
    path:     /delete
    methods:  [DELETE]
    defaults: { _controller: AdminWebMailBundle:Domain:deleteDomain }

update_domains:
    path:     /update
    methods:  [PUT]
    defaults: { _controller: AdminWebMailBundle:Domain:updateUpdate }